-- HE CREADO LA TABLA HITO1:
CREATE DATABASE IF NOT EXISTS HITO1;
-- LA HE PUESTO EN USO:
USE HITO1;
-- HE CREADO UNA TABLA ALUMNOS CON LOS SIGUIENTES CAMPOS:
 CREATE TABLE ALUMNOS (
    DNI CHAR(20) PRIMARY KEY,
    NOMBRE CHAR(30),
    APELLIDOS CHAR(60),
    FECHA_DE_NACIMIENTO DATE,
    CORREO_ELECTRÓNICO CHAR(60),
    TELÉFONO INT(20),
    DIRECCIÓN CHAR(80),
    CIUDAD CHAR(60),
    PROVINCIA CHAR(60),
    CÓDIGO_POSTAL INT(15),
    ACEPTADO BOOLEAN);

